### ISSUE TITLE
handle mboxes without a terminal blank

### ISSUE THREAD

**Issue by rjbs** [Perl-Email-Project/Email-Folder#2]
See also https://rt.cpan.org/Ticket/Display.html?id=52854

**Comment by pali** [comment]
My commit https://github.com/pali/Email-Folder/commit/5f3478796878545cf2b5a695fee1735b09849816 which is part of pull request https://github.com/rjbs/Email-Folder/pull/5 should fix this problem.

**Comment by pali** [comment]
Fixed.
